sonar.projectKey=cloudwithabhoy_devsecops-eks-pipeline
sonar.organization=cloudwithabhoy
sonar.projectName=devsecops-eks-pipeline

sonar.sources=app
sonar.exclusions=**/node_modules/**,**/test/**,**/*.spec.ts,**/dist/**