sonar.projectKey=<YOUR_GITHUB_USERNAME>_devsecops-eks-pipeline
sonar.organization=<YOUR_SONARCLOUD_ORG>
sonar.projectName=devsecops-eks-pipeline

sonar.sources=app
sonar.exclusions=**/node_modules/**,**/test/**,**/*.spec.ts,**/dist/**