replicaCount: 1
image:
  repository: 637423496001.dkr.ecr.ap-south-1.amazonaws.com/devsecops-eks-dev
  tag: 60e72b830caa7ed0b083568a6916bdb557b84630
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  host: ""
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
