replicaCount: 1
image:
  repository: ""
  tag: 1bc494feeeed44b45fc423aba290bd27c8acd196
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  host: ""
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
