apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-juice-shop
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000